CREATE TABLE IF NOT EXISTS public.company (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    email varchar(100) NOT NULL UNIQUE,
    phone_number varchar(12) NOT NULL UNIQUE,
    description varchar
);

ALTER TABLE IF EXISTS public.company OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    price double precision CHECK(price >= 1) NOT NULL,
    description varchar,
    company_id bigint REFERENCES company(id) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS public.product OWNER to postgres;


